#cloud-config
package_update: true
package_upgrade: true

runcmd:
  - sudo sed -i.bak -E '/^URIs:/ { N; /Suites:.*-security/! { s@http://(jp\.)?archive\.ubuntu\.com/ubuntu/?@http://ftp.udx.icscoe.jp/Linux/ubuntu/@; s@http://(jp\.)?ports\.ubuntu\.com/ubuntu-ports/?@http://ftp.udx.icscoe.jp/Linux/ubuntu-ports/@; } }' /etc/apt/sources.list.d/ubuntu.sources
  - apt-get update
  - apt-get upgrade -y

power_state:
  delay: 5
  mode: reboot
  message: "Rebooting after system update"
  timeout: 120
