---
- name: Create bootstrap token
  shell: "echo $(openssl rand -hex 3).$(openssl rand -hex 8)"
  register: bootstrap_token
  when: groups['master'][0] == inventory_hostname
- name: Copy kubeadm init config
  template:
    src: templates/init_kubelet.yaml.j2
    dest: /tmp/init_kubelet.yaml
  when: groups['master'][0] == inventory_hostname
- name: Initialize kubeadm
  command: kubeadm init --upload-certs --config=/tmp/init_kubelet.yaml
  when: groups['master'][0] == inventory_hostname

- name: Get kube admin config
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: outputs
  when: groups['master'][0] == inventory_hostname

- name: Create keyrings directory
  file:
    state: directory
    path: ~/.kube
    mode: 0755
- name: Make directory for .kube
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: true
  when: groups['master'][0] == inventory_hostname

- name: Generate certificate key
  command: kubeadm init phase upload-certs --upload-certs
  register: cert_key
  when: groups['master'][0] == inventory_hostname
- name: Generate token
  command: kubeadm token create
  register: token
  when: groups['master'][0] == inventory_hostname
- name: Get discovery token CA cert hash
  shell: |
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | \
      openssl rsa -pubin -outform der 2>/dev/null | \
      openssl dgst -sha256 -hex | sed 's/^.* //'
  register: ca_cert_hash
  when: groups['master'][0] == inventory_hostname
- name: Set token
  set_fact:
    k8s_token: "{{ token.stdout }}"
    k8s_ca_cert_hash: "{{ ca_cert_hash.stdout }}"
    k8s_cert_key: "{{ cert_key.stdout }}"
  when: groups['master'][0] == inventory_hostname
