---
- name: Save worker config file
  template:
    src: init_join.yaml.j2
    dest: /tmp/init_join.yaml
- name: Join the cluster
  command: kubeadm join --config=/tmp/init_join.yaml
  register: join_result